config/routes.rb
Roomie::Application.routes.draw do

  root :to => 'dashboard#index'

  # route to join a dwelling using an invite url
  match 'invites/:token/accpet' => 'invites#accept', :as => 'invites_accept'
  match 'invites/:token' => 'invites#show', :as => 'invites'

  # Dwellings
  resources :dwellings, except: :index do
    resources :invites, :controller => 'dwelling_invites', :except => [:show, :edit, :update]
  end

  # Bills
  get 'payments' => 'bill_payments#history', :as => 'history'
  resources :bills do
    resources :comments
    resources :bill_payments
  end

  # Shopping Lists
  resources :shopping_lists do
    resources :comments
    resources :shopping_list_items
  end

  # Chores
  put 'chores/:id/deactivate' => 'chores#deactivate', :as => "deactivate_chore"
  resources :chores do
    resources :comments
  end

  # Events
  resources :events do
    resources :comments
  end

  # Comments
  resources :comments do
    resources :comments
  end

  # Posts
  resources :posts do
    resources :comments
  end

  # Users and signup
  get 'signup' => 'users#new', :as => 'signup'
  resources :users, :except => [:index, :edit, :update] do
    member do
      
      [:account, :profile, :picture, :notifications].each do |type|
        get "settings/#{type}" => "user_settings#edit_#{type}", as: "#{type}_settings"
        put "settings/#{type}" => "user_settings#update_#{type}"
      end
    end
  end
  
  # Login / Logout
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/invite.rb
class Invite < ActiveRecord::Base
	# Relations
  belongs_to :dwelling

	# Validations
  validates_presence_of :dwelling, :email
  validates_uniqueness_of :email, :scope => :dwelling_id,
    :message => 'An invite has already been seent to this email'

	# Callbacks
  before_create :generate_token

	# Accessible Attributes
  attr_accessible :email, :token, :dwelling_id


	private

	# create a validation token
  def generate_token
    self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
  end
end

app/controllers/invites_controller.rb
# Controller for accepting dwelling invites
class InvitesController < ApplicationController
  # You have to be logged in to accept an invite
  before_filter :logged_in?, :except => :show

  # GET /invites/show
  def show
    @invite = Invite.find_by_token(params[:token])
    if @invite
      @dwelling = @invite.dwelling
    end

    respond_to do |format|
      format.html # show.html.haml
    end
  end

  # Add the user to the dwelling they were
  # invited to.
  # GET /invites/:token/accept
  def accept
    @invite = Invite.find_by_token(params[:token])
    if @invite
      current_user.dwelling = @invite.dwelling
      current_user.save!
    end
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to 404 } unless @invite
      if current_user.save
        format.html { redirect_to root_path }
      else
        format.html { render action: 'show',
          notice: 'There was a problem adding you to the dwelling.' }
      end
    end
  end
end

app/views/invites/_form.html.haml
= form_for @invite do |f|
  - if @invite.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invite.errors.count, "error")} prohibited this invite from being saved:"
      %ul
        - @invite.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :dwelling
    = f.text_field :dwelling_id
  .field
    = f.label :invitee
    = f.text_field :invitee_id
  .field
    = f.label :invitee_email
    = f.text_field :invitee_email
  .actions
    = f.submit 'Save'

app/views/invites/accept.html.haml
%h1 Accept Invitation

%p
  You have been invited to join #{@dwelling.name}. Do you know any of these people?
  %ul
  - for user in @dwelling.users
    %li= link_to user.name, user_path(user)

= link_to 'Join Dwelling', invites_accept_path(@invite)

app/views/invites/new.html.haml
%h1 New invite

= render 'form'

= link_to 'Back', invites_path

app/views/invites/show.html.haml
%h1 Accept Invitation

%p
  You have been invited to join #{@dwelling.name}. Do you know any of these people?
  %ul
  - for user in @dwelling.users
    %li= link_to user.name, user_path(user)

= link_to 'Join Dwelling', invites_accept_path(@invite.token)