config/routes.rb
Roomie::Application.routes.draw do

  root :to => 'dashboard#index'

  # route to join a dwelling using an invite url
  match 'invites/:token/accpet' => 'invites#accept', :as => 'invites_accept'
  match 'invites/:token' => 'invites#show', :as => 'invites'

  # Dwellings
  resources :dwellings, except: :index do
    resources :invites, :controller => 'dwelling_invites', :except => [:show, :edit, :update]
  end

  # Bills
  get 'payments' => 'bill_payments#history', :as => 'history'
  resources :bills do
    resources :comments
    resources :bill_payments
  end

  # Shopping Lists
  resources :shopping_lists do
    resources :comments
    resources :shopping_list_items
  end

  # Chores
  put 'chores/:id/deactivate' => 'chores#deactivate', :as => "deactivate_chore"
  resources :chores do
    resources :comments
  end

  # Events
  resources :events do
    resources :comments
  end

  # Comments
  resources :comments do
    resources :comments
  end

  # Posts
  resources :posts do
    resources :comments
  end

  # Users and signup
  get 'signup' => 'users#new', :as => 'signup'
  resources :users, :except => [:index, :edit, :update] do
    member do
      
      [:account, :profile, :picture, :notifications].each do |type|
        get "settings/#{type}" => "user_settings#edit_#{type}", as: "#{type}_settings"
        put "settings/#{type}" => "user_settings#update_#{type}"
      end
    end
  end
  
  # Login / Logout
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/shopping_list_item.rb
class ShoppingListItem < ActiveRecord::Base
	# Relations
  belongs_to :shopping_list
	# Accessible Attributes
  attr_accessible :name, :obligate_id, :obligates, :quantity, :shopping_list_id, :status

	# Validations
  validates :name, :presence => true
end

app/controllers/shopping_list_items_controller.rb
class ShoppingListItemsController < ApplicationController
  before_filter :get_shopping_list_of_item

  def index
    @shopping_list_items = ShoppingListItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shopping_list_items }
    end
  end

  # GET /shopping_list_items/1
  # GET /shopping_list_items/1.json
  def show
    @shopping_list_item = @shopping_list.shopping_list_items.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shopping_list_item }
    end
  end

  # GET /shopping_list_items/new
  # GET /shopping_list_items/new.json
  def new
    @shopping_list_item = @shopping_list.shopping_list_items.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shopping_list_item }
    end
  end

  # GET /shopping_list_items/1/edit
  def edit
    @shopping_list_item = @shopping_list.shopping_list_items.find(params[:id])
  end

  # POST /shopping_list_items
  # POST /shopping_list_items.json
  def create
    @shopping_list_item = @shopping_list.shopping_list_items.new(params[:shopping_list_item])

    respond_to do |format|
      if @shopping_list_item.save
        format.html { redirect_to shopping_list_path(@shopping_list_item.shopping_list_id), notice: 'Shopping list item was successfully created.' }
        format.json { render json: @shopping_list_item, status: :created, location: @shopping_list_item }
      else
        format.html { render :new }
        format.json { render json: @shopping_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shopping_list_items/1
  # PUT /shopping_list_items/1.json
  def update
    @shopping_list_item = @shopping_list.shopping_list_items.find(params[:id])
    respond_to do |format|
      if @shopping_list_item.update_attributes(params[:shopping_list_item])
        format.html { redirect_to shopping_list_path(@shopping_list_item.shopping_list_id), notice: 'Shopping list item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @shopping_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_list_items/1
  # DELETE /shopping_list_items/1.json
  def destroy
    @shopping_list_item = @shopping_list.shopping_list_items.find(params[:id])
    @shopping_list_item.destroy

    respond_to do |format|
      format.html { redirect_to @shopping_list}
      format.json { head :no_content }
    end
  end

  private

  def get_shopping_list_of_item
    @shopping_list = ShoppingList.find(params[:shopping_list_id])

  end
end

app/views/shopping_list_items/_form.html.haml
= form_for [@shopping_list, @shopping_list_item] do |f|
  - if @shopping_list_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shopping_list_item.errors.count, "error")} prohibited this shopping_list_item from being saved:"
      %ul
        - @shopping_list_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.hidden_field :shopping_list_id, value: params[:shopping_list_id]
  .actions
    = f.submit 'Save'

app/views/shopping_list_items/edit.html.haml
%h1
  ="Edit item"

= render 'form'
= link_to 'Delete', shopping_list_shopping_list_item_path(@shopping_list_item, :shopping_list_id => @shopping_list.id), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-small'
= link_to 'Back', shopping_list_path(@shopping_list_item.shopping_list_id)

app/views/shopping_list_items/index.html.haml
%h1 Listing shopping_list_items

%table
  %tr
    %th Name
    %th Quantity
    %th Obligate
    %th Obligates
    %th Status
    %th Shopping list
    %th
    %th
    %th

  - @shopping_list_items.each do |shopping_list_item|
    %tr
      %td= shopping_list_item.name
      %td= shopping_list_item.quantity
      %td= shopping_list_item.obligate_id
      %td= shopping_list_item.obligates
      %td= shopping_list_item.status
      %td= shopping_list_item.shopping_list_id
      %td= link_to 'Show', shopping_list_item
      %td= link_to 'Edit', edit_shopping_list_item_path(shopping_list_item)
      %td= link_to 'Destroy', shopping_list_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Shopping list item', new_shopping_list_item_path

app/views/shopping_list_items/new.html.haml
%h1
  Add an item to #{@shopping_list.name}

= render 'form'

= link_to 'Cancel', shopping_list_path(@shopping_list)

app/views/shopping_list_items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @shopping_list_item.name
%p
  %b Quantity:
  = @shopping_list_item.quantity
%p
  %b Obligate:
  = @shopping_list_item.obligate_id
%p
  %b Obligates:
  = @shopping_list_item.obligates
%p
  %b Status:
  = @shopping_list_item.status
%p
  %b Shopping list:
  = @shopping_list_item.shopping_list_id

= link_to 'Edit', edit_shopping_list_shopping_list_item_path(@shopping_list_item)
\|
= link_to 'Back', shopping_list_path(id: @shopping_list_item.shopping_list_id)