config/routes.rb
Roomie::Application.routes.draw do

  root :to => 'dashboard#index'

  # route to join a dwelling using an invite url
  match 'invites/:token/accpet' => 'invites#accept', :as => 'invites_accept'
  match 'invites/:token' => 'invites#show', :as => 'invites'

  # Dwellings
  resources :dwellings, except: :index do
    resources :invites, :controller => 'dwelling_invites', :except => [:show, :edit, :update]
  end

  # Bills
  get 'payments' => 'bill_payments#history', :as => 'history'
  resources :bills do
    resources :comments
    resources :bill_payments
  end

  # Shopping Lists
  resources :shopping_lists do
    resources :comments
    resources :shopping_list_items
  end

  # Chores
  put 'chores/:id/deactivate' => 'chores#deactivate', :as => "deactivate_chore"
  resources :chores do
    resources :comments
  end

  # Events
  resources :events do
    resources :comments
  end

  # Comments
  resources :comments do
    resources :comments
  end

  # Posts
  resources :posts do
    resources :comments
  end

  # Users and signup
  get 'signup' => 'users#new', :as => 'signup'
  resources :users, :except => [:index, :edit, :update] do
    member do
      
      [:account, :profile, :picture, :notifications].each do |type|
        get "settings/#{type}" => "user_settings#edit_#{type}", as: "#{type}_settings"
        put "settings/#{type}" => "user_settings#update_#{type}"
      end
    end
  end
  
  # Login / Logout
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/bill.rb
class Bill < DwellingItem
	# Accessible Attributes
  attr_accessible :amount, :date_due, :name, :owed_to, :status, :dwelling_id

	# Scopes
	scope :upcoming, order(:date_due).where(['date_due >= ?', Date.today])

	# Relations
  has_many :bill_payments
  has_many :users, :through => :dwelling

	# Validations
  validates :amount, :numericality => {:greater_than_or_equal_to => 0}
  validates :date_due, :presence => true
  validates :name, :presence => true
  validates :owed_to, :presence => true

	# filters
  after_initialize :init

  def init
    self.status ||= :unpaid
  end

  def payment_sum
    payment_sum = 0
    self.bill_payments.each do |payment|
      payment_sum += payment.amount
    end
    return payment_sum
  end

  def payment_percentage
    return (self.payment_sum/self.amount)*100.to_int
  end
end

app/controllers/bills_controller.rb
class BillsController < DwellingItemsController
  before_filter :get_dwelling_and_bill
	before_filter :ensure_bill_belongs_to_current_user, only: [:edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = @dwelling.bills

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    # calculate bill payment information
    @payment_sum = 0
    @bill.bill_payments.each do |payment|
      @payment_sum += payment.amount
    end
    @percentage = (@payment_sum/@bill.amount)*100.to_int

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = @dwelling.bills.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = @dwelling.bills.build(params[:bill])
    @bill.owner = current_user

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bill_path(@bill), notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
				format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to bill_path(@bill), notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_path }
      format.json { head :no_content }
    end
  end

	private

  def get_dwelling_and_bill
    @dwelling = current_dwelling
    if params[:id]
      @bill = @dwelling.bills.find(params[:id])
    end
  end

	def ensure_bill_belongs_to_current_user
		permission_denied unless current_user == @bill.owner
	end
end

app/views/bills/_details.html.haml
.bill-container
  %h4
    = bill.name
    %small
      = ' - ' + bill.owed_to
    %small.pull-right
      = bill.owner.name
  .bill-details
    %span.amount-due
      %p
        Amount Due
      %h3
        = number_to_currency(bill.amount, :unit => "$")
    %span.date-due
      %p
        Date Due
      %h3
        = bill.date_due.month.to_s + '/' + bill.date_due.day.to_s + '/' + bill.date_due.year.to_s
        - date_rem = (bill.date_due - Date.today).to_i
        - if date_rem == 0
          %small (Today)
        - elsif date_rem < 0
          %small= "(Overdue " + (-date_rem).to_s + " days)"
        - else
          %small= "("+date_rem.to_s + " days)"
    %span.status
      %p
        Status
      - payment_sum = bill.payment_sum
      %h3{:class => (payment_sum < bill.amount ? 'unpaid' : 'paid')}
        = (payment_sum < bill.amount ? 'unpaid' : 'paid')
    .show-bill-options
      .contents
        = link_to 'Show', bill_path(bill), class: 'btn btn-success btn-small'
        - if current_user == bill.owner
          = link_to 'Edit', edit_bill_path(bill), class: 'btn btn-warning btn-small'
          = link_to 'Destroy', bill_path(bill), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-small'
%br

app/views/bills/_form.html.haml
= form_for @bill do |f|
  - if @bill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bill.errors.count, "error")} prohibited this bill from being saved:"
      %ul
        - @bill.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :owed_to
    = f.text_field :owed_to
  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :date_due
    = calendar_datepicker(:date_due, f)
  .field
    = f.label :status
    = f.text_field :status
  .actions
    = f.submit 'Save'

app/views/bills/edit.html.haml
%h1 Editing bill

= render 'form'

= link_to 'Show', bill_path(@bill)
\|
= link_to 'Back', bills_path

app/views/bills/index.html.haml
.body-container
  %h1
    Upcoming Bills
  - @bills.each do |bill|
    = render 'bills/details', bill: bill
  .new-bill
    = link_to 'New Bill', new_bill_path, class: 'btn btn-inverse btn-block'

app/views/bills/new.html.haml
%h1 New bill

= render 'form'

= link_to 'Back', bills_path

app/views/bills/show.html.haml
= render 'bills/details', bill: @bill

.body-container
  .feed-container
    .inner-body
      .feed-info-container
        %br
        = render 'comments/all', dwelling_item: @bill

%hr
= link_to 'Back', bills_path