config/routes.rb
Roomie::Application.routes.draw do

  root :to => 'dashboard#index'

  # route to join a dwelling using an invite url
  match 'invites/:token/accpet' => 'invites#accept', :as => 'invites_accept'
  match 'invites/:token' => 'invites#show', :as => 'invites'

  # Dwellings
  resources :dwellings, except: :index do
    resources :invites, :controller => 'dwelling_invites', :except => [:show, :edit, :update]
  end

  # Bills
  get 'payments' => 'bill_payments#history', :as => 'history'
  resources :bills do
    resources :comments
    resources :bill_payments
  end

  # Shopping Lists
  resources :shopping_lists do
    resources :comments
    resources :shopping_list_items
  end

  # Chores
  put 'chores/:id/deactivate' => 'chores#deactivate', :as => "deactivate_chore"
  resources :chores do
    resources :comments
  end

  # Events
  resources :events do
    resources :comments
  end

  # Comments
  resources :comments do
    resources :comments
  end

  # Posts
  resources :posts do
    resources :comments
  end

  # Users and signup
  get 'signup' => 'users#new', :as => 'signup'
  resources :users, :except => [:index, :edit, :update] do
    member do
      
      [:account, :profile, :picture, :notifications].each do |type|
        get "settings/#{type}" => "user_settings#edit_#{type}", as: "#{type}_settings"
        put "settings/#{type}" => "user_settings#update_#{type}"
      end
    end
  end
  
  # Login / Logout
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/chore.rb
class Chore < DwellingItem
	# Accessible Attributes
  attr_accessible :assigned_user_id, :description, :dwelling_id, :name, :active, :cron_str

	# Relations
  belongs_to :assigned_user, :class_name => 'User'

	# Validations
  validates :name, :length => {:minimum => 1}

  # Scope
  scope :active, where(:active => true)
  scope :inactive, where(:active => false)
end

app/controllers/chores_controller.rb
class ChoresController < DwellingItemsController
  before_filter :get_dwelling_and_chore
	before_filter :ensure_chore_belongs_to_current_user, only: [:edit, :update, :destroy]

  # GET /chores
  # GET /chores.json
  def index
    if params[:inactive]
      @chores = @dwelling.chores.inactive
    else
      @chores = @dwelling.chores.active
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chores }
    end
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/new
  # GET /chores/new.json
  def new
    @chore = Chore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = @dwelling.chores.build(params[:chore])
    @chore.owner = current_user
    @chore.active = true

    # Make the actual cron-format string
    cron_cmd = "/bin/bash -l -c 'cd #{Rails.root} && bundle exec rake chores:activate_chore CHORE_ID="
    case @chore.cron_str
    when "Every M/W/F"
      @chore.cron_str = "0 0 * * MON,WED,FRI #{cron_cmd}"
    when "Every T/Th"
      @chore.cron_str = "0 0 * * TUE,THU #{cron_cmd}"
    when "Every Sunday"
      @chore.cron_str = "0 0 * * SUN #{cron_cmd}"
    else
      @chore.cron_str = nil
    end

    # if @chore.cron_str
    #   puts @chore.cron_str
    #   puts (CronEdit::Crontab.Add "chore_#{params[:id]}", @chore.cron_str)
    # end

    respond_to do |format|
      if @chore.save
        if @chore.cron_str
          puts @chore.cron_str
          puts (CronEdit::Crontab.Add "chore_#{@chore.id}", "#{@chore.cron_str}#{@chore.id}'")
        end
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render json: @chore, status: :created, location: @chore }
      else
        format.html { render :new }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chores/1
  # PUT /chores/1.json
  def update
    # TODO: Add cron_str updating
    respond_to do |format|
      if @chore.update_attributes(params[:chore])
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    if @chore.cron_str
      puts "Removing #{@chore.id} from crontab #{@chore.cron_str}"
      CronEdit::Crontab.Remove "chore_#{@chore.id}"
    end

    @chore.destroy

    respond_to do |format|
      format.html { redirect_to chores_url }
      format.json { head :no_content }
    end
  end

  # PUT /chores/1/deactivate
  # PUT /chores/1/deactivate.json
  def deactivate
    permission_denied unless @chore.active
    @chore.update_attribute(:active, false)
    redirect_to chores_url, notice: "Chore was successfully deactivated"
  end

  private

  # Assign @dwelling and @chore if applicable
  def get_dwelling_and_chore
    @dwelling = current_dwelling
    if params[:id]
      @chore = @dwelling.chores.find(params[:id])
    end
  end

  def ensure_chore_belongs_to_current_user
    permission_denied unless current_user == @chore.owner
  end

end

app/views/chores/_details.html.haml
%li
  / %a#view-chore{:href => chore_url(chore)}
  .chore-obligate
    - if current_user == chore.owner
      .delete-chore
        %a=link_to 'X', chore, :method => :delete, :data => { :confirm => 'Are you sure?'}
    = chore.assigned_user.name if chore.assigned_user
  .chore-title
    = chore.name
  .chore-description
    = chore.description
  .chore-state
    - if chore.active && (current_user == chore.assigned_user || current_user == chore.owner)
      = link_to [:deactivate, chore], :method => :put do
        = chore.active ? "(Active)" : "(Inactive)"
    - else
      = chore.active ? "(Active)" : "(Inactive)"
  - if current_user == chore.owner
    .edit-chore
      = link_to [:edit, chore] do
        %i.icon-edit
  .chore-owner
    = "- #{chore.owner.first_name or chore.owner.email}"

app/views/chores/_form.html.haml
= form_for @chore do |f|
  - if @chore.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chore.errors.count, "error")} prohibited this chore from being saved:"
      %ul
        - @chore.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :assigned_user_id
    = f.collection_select :assigned_user_id, @dwelling.users, :id, :name
  .field
    = f.label :when
    = f.select :cron_str, ["Just Once", "Every M/W/F", "Every T/Th", "Every Sunday"]
    = f.submit 'Save'

app/views/chores/edit.html.haml
%h1 Editing chore

= render 'form'

= link_to 'Show', @chore
\|
= link_to 'Back', chores_path

app/views/chores/index.html.haml
/ %h1 DONT BE LAZY!


/ %br

/ %ul.chores
/ 	- @chores.active.each do |chore|
/ 		= render 'chores/details', chore: chore


/ = link_to 'New Chore', new_chore_path


.feed-container
	.inner-body
		.feed-info-container
			%h1 Chores
			.new-event
				= link_to 'New Chore', new_chore_path, class: 'btn btn-block btn-inverse'
			%ul.nav.nav-tabs
				%li{class: !params[:inactive] ? :active : nil}
					= link_to :active, chores_path
				%li{class: params[:inactive] ? :active : nil}
					= link_to :inactive, chores_path(inactive: true)
			/ - @chores.each do |chore|
			/ 	= render 'chores/details', chore: chore
			%ul.chores
				- @chores.each do |chore|
					= render 'chores/details', chore: chore

app/views/chores/new.html.haml
%h1 New chore

= render 'form'

= link_to 'Back', chores_path

app/views/chores/show.html.haml
%p#notice= notice

%ul.chores
  = render 'chores/details', chore: @chore

.body-container
  .feed-container
    .inner-body
      .feed-info-container
        %br
        = render 'comments/all', dwelling_item: @chore

  = link_to 'Edit', edit_chore_path(@chore)
  \|
  = link_to 'Back', chores_path